services:
  db:
    container_name: devices-springboot
    image: postgres:latest
    environment:
      POSTGRES_USER: nulhart
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5333:5432"
    networks:
      - db
    restart: unless-stopped

  app:
      build: .
      container_name: devices-springboot-app
      ports:
        - "8080:8080"
      depends_on:
        - db
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
        SPRING_DATASOURCE_USERNAME: nulhart
        SPRING_DATASOURCE_PASSWORD: password
      networks:
        - db
      restart: unless-stopped

networks:
   db:
     driver: bridge

volumes:
  db:
